name: Send Mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello world
      run: echo "Hello World"

    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.gmail.com
        port: 465
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: Hinata K
        from: ${{secrets.MAIL_ADDRESS}}
        to: kalaiarasan12rj@gmail.com
        subject: Action mail
        body: Hey Everybody
        contentType: text/plain